// Catálogo ficticio de demostración. Coordenadas sobre la fotografía de 1536 × 1024.
// Cada disco suena como un canal en vivo de SomaFM (radio independiente, sostenida por sus oyentes: https://somafm.com).
export const records = [
  { id: "solar", title: "Solar", artist: "El Sur", genre: "Psicodelia", year: "1974", color: "#d76b3b", crop: [77, 49, 435, 421], station: { id: "groovesalad", name: "Groove Salad" }, description: "Guitarras que se estiran como la luz de la tarde. Un viaje cálido y sin apuro entre el rock psicodélico y los paisajes del sur.", tracks: ["Luz de enero", "Al otro lado del sol", "La siesta", "Hasta desaparecer"] },
  { id: "blue-hours", title: "Blue Hours", artist: "The Sunday Quartet", genre: "Jazz", year: "1968", color: "#668ca8", crop: [547, 50, 437, 420], station: { id: "sonicuniverse", name: "Sonic Universe" }, description: "Un piano, una trompeta y la ciudad bajando el volumen. Cuatro músicos se encuentran en ese instante en el que la noche todavía no termina.", tracks: ["A Quiet Corner", "Sunday, 5 AM", "The Long Way Home", "Blue Hours"] },
  { id: "after-dark", title: "After Dark", artist: "Luna", genre: "Ambient", year: "1982", color: "#b96e5c", crop: [1020, 49, 436, 421], station: { id: "deepspaceone", name: "Deep Space One" }, description: "Sintetizadores suspendidos y pequeñas señales desde lejos. Música para mirar por la ventana cuando el resto del mundo duerme.", tracks: ["Órbita", "Luces lejanas", "El lado invisible", "Después de todo"] },
  { id: "jardin", title: "Jardín", artist: "Casa Abierta", genre: "Latin", year: "1976", color: "#879565", crop: [74, 498, 437, 446], station: { id: "illstreet", name: "Illinois Street Lounge" }, description: "Percusiones de madera, bajos redondos y ventanas abiertas. Una celebración pequeña de las plantas, las personas y los días que empiezan bien.", tracks: ["Puertas abiertas", "Monstera", "La sobremesa", "Verde adentro"] },
  { id: "soft-signal", title: "Soft Signal", artist: "Forma", genre: "Ambient", year: "1991", color: "#b888a1", crop: [545, 499, 439, 445], station: { id: "spacestation", name: "Space Station Soma" }, description: "Texturas que se doblan y melodías que casi se pueden tocar. Electrónica íntima para encontrar un poco de espacio entre tanto ruido.", tracks: ["First Contact", "Slow Geometry", "Almost Here", "Soft Signal"] },
  { id: "frecuencia", title: "Frecuencia", artist: "Estudio 84", genre: "Electrónica", year: "1984", color: "#cba962", crop: [1020, 499, 440, 446], station: { id: "fluid", name: "Fluid" }, description: "Cajas de ritmo, líneas de bajo y una idea sencilla: seguir moviéndose. Una exploración analógica del pulso y la repetición.", tracks: ["Señal uno", "Movimiento continuo", "84 BPM", "Otra frecuencia"] },
] as const;
export type RecordItem = typeof records[number];
